# Generated by Django 3.2.4 on 2022-05-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0034_auto_20220501_0545'),
        ('requirement', '0010_alter_requirementchangehistory_change_count'),
        ('user', '0007_departmentequivalent_majorequivalent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_required_credit', models.PositiveIntegerField(default=0)),
                ('curr_required_credit', models.PositiveIntegerField(default=0)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementchangehistory', to='requirement.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTypeChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
                ('past_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('curr_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='lecture.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='user.major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
                ('year_taken', models.IntegerField(default=0)),
                ('past_credit', models.PositiveIntegerField(default=0)),
                ('curr_credit', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='lecture.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='user.major')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
