# Generated by Django 3.1 on 2021-02-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_credit_requirement', models.BooleanField()),
                ('required_credit', models.PositiveSmallIntegerField(default=0)),
                ('requirement_type', models.PositiveSmallIntegerField(choices=[(1, 'general'), (2, 'major_requirement'), (3, 'major_elective'), (4, 'all'), (5, 'none')])),
                ('lecture_type_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'base_of_study'), (3, 'world_of_study'), (4, 'other')], default=1)),
                ('lecture_type_detail_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'thought_and_expression'), (3, 'foreign_languages'), (4, 'mathematical_analysis_and_reasoning'), (5, 'scientific_thinking_and_experiment'), (6, 'computer and informatics'), (7, 'language and literature'), (8, 'culture and arts'), (9, 'history and philosophy'), (10, 'politics and economics'), (11, 'humanity and society'), (12, 'nature and technology'), (13, 'life and environment')], default=1)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='user.major')),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='PlanRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('earned_credit', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrequirement', to='lecture.plan')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrequirement', to='requirement.requirement')),
            ],
        ),
    ]