# Generated by Django 3.1 on 2021-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='lecture_type_detail',
            new_name='requirement_type_detail',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='lecture_type_detail_detail',
            new_name='requirement_type_detail_detail',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'major_requirement'), (3, 'major_elective'), (4, 'general'), (5, 'all')]),
        ),
    ]
