# Generated by Django 3.1 on 2021-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0002_auto_20210702_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequirement',
            name='auto_calculate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planrequirement',
            name='required_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
