# Generated by Django 3.1 on 2021-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_auto_20210319_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_type_detail',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_type_detail_detail',
        ),
    ]
