# Generated by Django 3.1 on 2021-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_auto_20210810_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_all', 'major_all'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching'), ('all', 'all')], max_length=50),
        ),
    ]
