# Generated by Django 3.1 on 2021-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0004_auto_20210810_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_credit_requirement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2014),
        ),
    ]
