# Generated by Django 3.1 on 2021-11-10 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0006_auto_20211107_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requirementchangehistory',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
