# Generated by Django 3.1 on 2021-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0007_auto_20211110_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequirement',
            name='is_updated_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
