# Generated by Django 3.1 on 2021-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0008_planrequirement_is_updated_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrequirement',
            name='is_updated_by_user',
        ),
    ]
