# Generated by Django 3.2.4 on 2022-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0009_remove_planrequirement_is_updated_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementchangehistory',
            name='change_count',
            field=models.IntegerField(default=0),
        ),
    ]
