# Generated by Django 3.2.4 on 2022-05-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('requirement', '0010_alter_requirementchangehistory_change_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrequirement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrequirement', to='plan.plan'),
        ),
        migrations.DeleteModel(
            name='RequirementChangeHistory',
        ),
    ]
