# Generated by Django 3.2.4 on 2022-05-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester_type', models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], max_length=50)),
                ('major_requirement_credit', models.PositiveSmallIntegerField(default=0)),
                ('major_elective_credit', models.PositiveSmallIntegerField(default=0)),
                ('general_credit', models.PositiveSmallIntegerField(default=0)),
                ('general_elective_credit', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='plan.plan')),
            ],
        ),
    ]
