# Generated by Django 3.1 on 2021-11-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
