# Generated by Django 3.2.4 on 2022-05-01 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_report', '0002_bugreport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
