# Generated by Django 3.2.4 on 2022-06-01 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(default='', max_length=50)),
                ('lecture_name', models.CharField(db_index=True, max_length=50)),
                ('open_department', models.CharField(max_length=50, null=True)),
                ('open_major', models.CharField(max_length=50, null=True)),
                ('open_semester', models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], default='unknown', max_length=50)),
                ('lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prev_lecture_name', models.CharField(max_length=50, null=True)),
                ('recent_open_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(db_index=True, max_length=50)),
                ('major_type', models.CharField(choices=[('major', 'major'), ('double_major', 'double_major'), ('minor', 'minor'), ('interdisciplinary_major', 'interdisciplinary_major'), ('interdisciplinary', 'interdisciplinary'), ('single_major', 'single_major'), ('interdisciplinary_major_for_teacher', 'interdisciplinary_major_for_teacher'), ('student_directed_major', 'student_directed_major'), ('interdisciplinary_program', 'interdisciplinary_program'), ('graduate_major', 'graduate_major')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MajorEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=50)),
                ('equivalent_major_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(db_index=True, default='새로운 계획', max_length=50)),
                ('is_first_simulation', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(default=2014)),
                ('end_year', models.PositiveSmallIntegerField(default=10000)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_credit_requirement', models.BooleanField(default=True)),
                ('required_credit', models.PositiveSmallIntegerField(default=0)),
                ('requirement_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_all', 'major_all'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching'), ('all', 'all')], max_length=50)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='core.major')),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester_type', models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], max_length=50)),
                ('major_requirement_credit', models.PositiveSmallIntegerField(default=0)),
                ('major_elective_credit', models.PositiveSmallIntegerField(default=0)),
                ('general_credit', models.PositiveSmallIntegerField(default=0)),
                ('general_elective_credit', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('lecture_type1', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('lecture_type2', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('recent_sequence', models.PositiveSmallIntegerField()),
                ('is_modified', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='core.lecture')),
                ('recognized_major1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='core.major')),
                ('recognized_major2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='core.major')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
                ('past_required_credit', models.PositiveIntegerField(default=0)),
                ('curr_required_credit', models.PositiveIntegerField(default=0)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementchangehistory', to='core.requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_credit', models.PositiveSmallIntegerField(default=0)),
                ('earned_credit', models.PositiveSmallIntegerField(default=0)),
                ('auto_calculate', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrequirement', to='core.plan')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrequirement', to='core.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planmajor', to='core.major')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planmajor', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='MajorLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majorlecture', to='core.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majorlecture', to='core.major')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTypeChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
                ('past_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('curr_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='core.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='core.major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField(default=0)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturecredit', to='core.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='CreditChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
                ('year_taken', models.IntegerField(default=0)),
                ('past_credit', models.PositiveIntegerField(default=0)),
                ('curr_credit', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='core.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='core.major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermajor', to='core.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermajor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'major')},
            },
        ),
        migrations.CreateModel(
            name='MajorDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majordepartment', to='core.department')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majordepartment', to='core.major')),
            ],
            options={
                'unique_together': {('department', 'major')},
            },
        ),
    ]
