# Generated by Django 3.2.4 on 2022-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planmajor',
            constraint=models.UniqueConstraint(fields=('plan', 'major'), name='planmajor_integrity_error'),
        ),
    ]
