# Generated by Django 3.1 on 2021-02-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(db_index=True, max_length=50)),
                ('major_type', models.PositiveSmallIntegerField(choices=[(1, 'double_major'), (2, 'minor'), (3, 'interdisciplinary_major'), (4, 'interdisciplinary'), (5, 'single_major'), (6, 'interdisciplinary_major_for_teacher_training_programs'), (7, 'student_directed_major')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'break')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermajor', to='user.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermajor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'major')},
            },
        ),
    ]
