# Generated by Django 3.1.6 on 2021-02-15 23:08

from django.db import migrations


def add_majors(apps, schema_editor):
    major=apps.get_model("user", "Major")
    majors=["철학과", "컴퓨터공학부", "언어학과", "물리학과", "영어교육과", "응용생물과학과", "독어독문과", "노어노문과", "종교학과", "지리교육과", "경제학과", "경영학과"]

    for i in range(0, 10):
        major.objects.create(major_name=majors[i], major_type=1)
        major.objects.create(major_name=majors[i], major_type=2)
        


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_majors)
    ]

