# Generated by Django 3.1 on 2021-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entrance_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_type',
            field=models.CharField(choices=[('major', 'major'), ('double_major', 'double_major'), ('minor', 'minor'), ('interdisciplinary_major', 'interdisciplinary_major'), ('interdisciplinary', 'interdisciplinary'), ('single_major', 'single_major'), ('interdisciplinary_major_for_teacher_training_programs', 'interdisciplinary_major_for_teacher_training_programs'), ('student_directed_major', 'student_directed_major')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('break', 'break')], default='active', max_length=50),
        ),
    ]
