# Generated by Django 3.1 on 2021-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210302_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_type',
            field=models.PositiveSmallIntegerField(choices=[('double_major', 'double_major'), ('minor', 'minor'), ('interdisciplinary_major', 'interdisciplinary_major'), ('interdisciplinary', 'interdisciplinary'), ('single_major', 'single_major'), ('interdisciplinary_major_for_teacher_training_programs', 'interdisciplinary_major_for_teacher_training_programs'), ('student_directed_major', 'student_directed_major')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('break', 'break')], default='active', max_length=50),
        ),
    ]
