# Generated by Django 3.1.12 on 2021-09-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210914_0207'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE FULLTEXT INDEX major_fulltext_index ON user_major(major_name) WITH PARSER ngram',
            reverse_sql='DROP INDEX major_fulltext_index ON user_major',
        )
    ]
