# Generated by Django 3.1 on 2021-11-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210926_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='major',
            name='major_type',
            field=models.CharField(choices=[('major', 'major'), ('double_major', 'double_major'), ('minor', 'minor'), ('interdisciplinary_major', 'interdisciplinary_major'), ('interdisciplinary', 'interdisciplinary'), ('single_major', 'single_major'), ('interdisciplinary_major_for_teacher', 'interdisciplinary_major_for_teacher'), ('student_directed_major', 'student_directed_major'), ('interdisciplinary_program', 'interdisciplinary_program')], max_length=100),
        ),
        migrations.CreateModel(
            name='MajorDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majordepartment', to='user.department')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majordepartment', to='user.major')),
            ],
            options={
                'unique_together': {('department', 'major')},
            },
        ),
    ]
