# Generated by Django 3.1 on 2021-11-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211109_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_type',
            field=models.CharField(choices=[('major', 'major'), ('double_major', 'double_major'), ('minor', 'minor'), ('interdisciplinary_major', 'interdisciplinary_major'), ('interdisciplinary', 'interdisciplinary'), ('single_major', 'single_major'), ('interdisciplinary_major_for_teacher', 'interdisciplinary_major_for_teacher'), ('student_directed_major', 'student_directed_major'), ('interdisciplinary_program', 'interdisciplinary_program'), ('graduate_major', 'graduate_major')], max_length=100),
        ),
    ]
