# Generated by Django 3.1 on 2021-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210525_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='year',
            new_name='entrance_year',
        ),
    ]
