# Generated by Django 3.1 on 2021-02-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(db_index=True, max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=False)),
                ('open_semester', models.PositiveSmallIntegerField(choices=[(1, 'unknown'), (2, 'first'), (3, 'second'), (4, 'summer'), (5, 'winter')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(db_index=True, max_length=50)),
                ('recent_scroll', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester_type', models.PositiveSmallIntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'summer'), (4, 'winter')])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='lecture.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_type', models.PositiveSmallIntegerField(choices=[(1, 'general'), (2, 'major_requirement'), (3, 'major_elective')])),
                ('lecture_type_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'base_of_study'), (3, 'world_of_study'), (4, 'other')], default=1)),
                ('lecture_type_detail_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'thought_and_expression'), (3, 'foreign_languages'), (4, 'mathematical_analysis_and_reasoning'), (5, 'scientific_thinking_and_experiment'), (6, 'computer and informatics'), (7, 'language and literature'), (8, 'culture and arts'), (9, 'history and philosophy'), (10, 'politics and economics'), (11, 'humanity and society'), (12, 'nature and technology'), (13, 'life and environment')], default=1)),
                ('recent_sequence', models.PositiveSmallIntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='lecture.lecture')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='lecture.semester')),
            ],
            options={
                'unique_together': {('semester', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='PlanMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planmajor', to='user.major')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planmajor', to='lecture.plan')),
            ],
            options={
                'unique_together': {('plan', 'major')},
            },
        ),
        migrations.CreateModel(
            name='MajorLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('lecture_type', models.PositiveSmallIntegerField(choices=[(1, 'general'), (2, 'major_requirement'), (3, 'major_elective')])),
                ('lecture_type_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'base_of_study'), (3, 'world_of_study'), (4, 'other')], default=1)),
                ('lecture_type_detail_detail', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'thought_and_expression'), (3, 'foreign_languages'), (4, 'mathematical_analysis_and_reasoning'), (5, 'scientific_thinking_and_experiment'), (6, 'computer and informatics'), (7, 'language and literature'), (8, 'culture and arts'), (9, 'history and philosophy'), (10, 'politics and economics'), (11, 'humanity and society'), (12, 'nature and technology'), (13, 'life and environment')], default=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majorlecture', to='lecture.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majorlecture', to='user.major')),
            ],
            options={
                'unique_together': {('major', 'lecture')},
            },
        ),
    ]
