# Generated by Django 3.1 on 2021-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(db_index=True, default='계획표', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recent_scroll',
            field=models.IntegerField(default=0),
        ),
    ]