# Generated by Django 3.1 on 2021-07-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210702_1254'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='semesterlecture',
            name='lecture_type_detail',
        ),
        migrations.RemoveField(
            model_name='semesterlecture',
            name='lecture_type_detail_detail',
        ),
        migrations.AddField(
            model_name='lecture',
            name='grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='lecture',
            name='open_department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='open_major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='prev_lecture_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='general_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='general_elective_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='major_elective_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='major_requirement_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='lecture_type1',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='lecture_type2',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='recognized_major1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='user.major'),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='recognized_major2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='user.major'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='open_semester',
            field=models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(db_index=True, default='새로운 계획', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recent_scroll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='majorlecture',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='lecture_type_detail',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='lecture_type_detail_detail',
        ),
    ]
