# Generated by Django 3.1 on 2021-02-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20210216_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]