# Generated by Django 3.1 on 2021-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_plan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type1',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type2',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
    ]
