# Generated by Django 3.1 on 2021-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20210705_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
