# Generated by Django 3.1 on 2021-09-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210702_1254'),
        ('lecture', '0005_auto_20210810_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_first_simulation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major1',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='user.major'),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major2',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='user.major'),
        ),
    ]
