# Generated by Django 3.1 on 2021-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20210309_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='open_department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='open_major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='past_lecture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='open_semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unknown'), (2, 'first'), (3, 'second'), (4, 'summer'), (5, 'winter'), (6, 'all')], default=1),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'general'), (2, 'major_requirement'), (3, 'major_elective'), (4, 'general_elective')]),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type_detail',
            field=models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'base_of_study'), (3, 'world_of_study'), (4, 'other'), (5, 'teaching')], default=1),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'general'), (2, 'major_requirement'), (3, 'major_elective'), (4, 'general_elective')]),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type_detail',
            field=models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'base_of_study'), (3, 'world_of_study'), (4, 'other'), (5, 'teaching')], default=1),
        ),
    ]
