# Generated by Django 3.1 on 2021-09-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20210902_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='recent_open_year',
            field=models.IntegerField(default=0),
        ),
    ]
