# Generated by Django 3.1 on 2021-03-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0006_auto_20210311_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='past_lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='prev_lecture_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='general_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='general_elective_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='major_elective_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='major_requirement_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='open_semester',
            field=models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type_detail',
            field=models.CharField(choices=[('none', 'none'), ('base_of_study', 'base_of_study'), ('world_of_study', 'world_of_study'), ('other', 'other')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type_detail_detail',
            field=models.CharField(choices=[('none', 'none'), ('thought_and_expression', 'thought_and_expression'), ('foreign_languages', 'foreign_languages'), ('mathematical_analysis_and_reasoning', 'mathematical_analysis_and_reasoning'), ('scientific_thinking_and_experiment', 'scientific_thinking_and_experiment'), ('computer_and_informatics', 'computer_and_informatics'), ('language_and_literature', 'language_and_literature'), ('culture_and_arts', 'culture_and_arts'), ('history_and_philosophy', 'history_and_philosophy'), ('politics_and_economics', 'politics_and_economics'), ('humanity_and_society', 'humanity_and_society'), ('nature_and_technology', 'nature_and_technology'), ('life_and_environment', 'life_and_environment')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(db_index=True, default='새로운 계획', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type_detail',
            field=models.CharField(choices=[('none', 'none'), ('base_of_study', 'base_of_study'), ('world_of_study', 'world_of_study'), ('other', 'other')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type_detail_detail',
            field=models.CharField(choices=[('none', 'none'), ('thought_and_expression', 'thought_and_expression'), ('foreign_languages', 'foreign_languages'), ('mathematical_analysis_and_reasoning', 'mathematical_analysis_and_reasoning'), ('scientific_thinking_and_experiment', 'scientific_thinking_and_experiment'), ('computer_and_informatics', 'computer_and_informatics'), ('language_and_literature', 'language_and_literature'), ('culture_and_arts', 'culture_and_arts'), ('history_and_philosophy', 'history_and_philosophy'), ('politics_and_economics', 'politics_and_economics'), ('humanity_and_society', 'humanity_and_society'), ('nature_and_technology', 'nature_and_technology'), ('life_and_environment', 'life_and_environment')], default='none', max_length=50),
        ),
    ]
