# Generated by Django 3.1 on 2021-03-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20210319_1111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='majorlecture',
            unique_together=set(),
        ),
    ]
