# Generated by Django 3.1.12 on 2021-09-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lecture_recent_open_year'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE FULLTEXT INDEX lecture_fulltext_index ON lecture_lecture(lecture_name) WITH PARSER ngram',
            reverse_sql='DROP INDEX lecture_fulltext_index ON lecture_lecture',
        )
    ]
