# Generated by Django 3.1 on 2021-10-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_lecturechangehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturechangehistory',
            name='count',
        ),
        migrations.AddField(
            model_name='lecturechangehistory',
            name='change_count',
            field=models.IntegerField(default=1),
        ),
    ]
