# Generated by Django 3.1 on 2021-05-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210525_0841'),
        ('lecture', '0009_semesterlecture_recognized_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterlecture',
            name='lecture_type_detail',
        ),
        migrations.RemoveField(
            model_name='semesterlecture',
            name='lecture_type_detail_detail',
        ),
        migrations.RemoveField(
            model_name='semesterlecture',
            name='recognized_major',
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='lecture_type1',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='lecture_type2',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='recognized_major1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='user.major'),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='recognized_major2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='user.major'),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], max_length=50),
        ),
    ]
