# Generated by Django 3.1 on 2021-11-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210926_0056'),
        ('lecture', '0010_auto_20211030_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('past_credit', models.PositiveIntegerField(default=0)),
                ('curr_credit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('change_count', models.IntegerField(default=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='lecture.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditchangehistory', to='user.major')),
            ],
        ),
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(default='', max_length=50)),
                ('lecture_name', models.CharField(db_index=True, max_length=50)),
                ('open_department', models.CharField(max_length=50, null=True)),
                ('open_major', models.CharField(max_length=50, null=True)),
                ('open_year', models.IntegerField(default=0)),
                ('open_semester', models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], default='unknown', max_length=50)),
                ('lecture_type', models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('professor_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectureTypeChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField(default=0)),
                ('past_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('curr_lecture_type', models.CharField(choices=[('none', 'none'), ('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('change_count', models.IntegerField(default=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='lecture.lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturetypechangehistory', to='user.major')),
            ],
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LectureChangeHistory',
        ),
    ]
