# Generated by Django 3.1 on 2021-05-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_auto_20210525_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorlecture',
            name='lecture_type_detail',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='lecture_type_detail_detail',
        ),
    ]
