# Generated by Django 3.1 on 2021-05-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_auto_20210525_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
