# Generated by Django 3.1 on 2021-11-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_auto_20211107_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField(default=0)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturecredit', to='lecture.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(default='', max_length=50)),
                ('lecture_name', models.CharField(db_index=True, max_length=50)),
                ('open_department', models.CharField(max_length=50, null=True)),
                ('open_major', models.CharField(max_length=50, null=True)),
                ('open_year', models.IntegerField(default=0)),
                ('open_semester', models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], default='unknown', max_length=50)),
                ('lecture_type', models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LectureHistory',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='credit',
        ),
        migrations.AddField(
            model_name='creditchangehistory',
            name='year_taken',
            field=models.IntegerField(default=0),
        ),
    ]
