# Generated by Django 3.1 on 2021-11-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_auto_20211107_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorLectureTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(default='', max_length=50)),
                ('major_type', models.CharField(default='', max_length=50)),
                ('lecture_code', models.CharField(default='', max_length=50)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('lecture_type', models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50)),
            ],
        ),
    ]
