# Generated by Django 3.1 on 2021-07-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210702_1227'),
        ('lecture', '0012_remove_plan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_id',
            new_name='lecture_code',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='prev_lecture_id',
            new_name='prev_lecture_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='semesterlecture',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type1',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type2',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major1',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='user.major'),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major2',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='user.major'),
        ),
    ]
