# Generated by Django 3.1 on 2021-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_majorlecturetmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturetmp',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
