# Generated by Django 3.1 on 2021-07-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210702_1227'),
        ('lecture', '0013_auto_20210702_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture1', to='user.major'),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='recognized_major2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture2', to='user.major'),
        ),
    ]
