# Generated by Django 3.2.6 on 2022-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_auto_20211115_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorlecture',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='lecture_type',
        ),
        migrations.RemoveField(
            model_name='majorlecture',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='majorlecturetmp',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='majorlecturetmp',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='majorlecturetmp',
            name='lecture_type',
        ),
        migrations.RemoveField(
            model_name='majorlecturetmp',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='lecturetypechangehistory',
            name='curr_lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturetypechangehistory',
            name='past_lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type1',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='semesterlecture',
            name='lecture_type2',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
    ]
