# Generated by Django 3.2.6 on 2022-03-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0017_auto_20220326_1536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('plan', 'year', 'semester_type')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_complete',
        ),
    ]
