# Generated by Django 3.2.6 on 2022-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0020_auto_20220411_0621'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='semester already exists in plan.',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('plan', 'year', 'semester_type'), name='semester already exists in plan.'),
        ),
    ]
