# Generated by Django 3.2.6 on 2022-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_auto_20220411_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorlecture',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='majorlecture',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorlecturetmp',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorlecturetmp',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorlecturetmp',
            name='lecture_type',
            field=models.CharField(choices=[('major_requirement', 'major_requirement'), ('major_elective', 'major_elective'), ('general', 'general'), ('general_elective', 'general_elective'), ('teaching', 'teaching')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='majorlecturetmp',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
