# Generated by Django 3.2.4 on 2022-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0022_auto_20220412_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditchangehistory',
            name='change_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturetypechangehistory',
            name='change_count',
            field=models.IntegerField(default=0),
        ),
    ]
