# Generated by Django 3.2.4 on 2022-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0024_auto_20220424_1355'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='semester already exists in plan.',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('plan', 'year', 'semester_type'), name='semester already exists in plan.'),
        ),
    ]
