# Generated by Django 3.2.4 on 2022-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0025_auto_20220424_1401'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planmajor',
            name='major already exists in major.',
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='semester already exists in plan.',
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_type', 'year')},
        ),
        migrations.AddConstraint(
            model_name='planmajor',
            constraint=models.UniqueConstraint(fields=('plan', 'major'), name='major already exists in plan.'),
        ),
    ]
