# Generated by Django 3.2.4 on 2022-04-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0026_auto_20220424_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('plan', 'semester_type', 'year')},
        ),
    ]
