# Generated by Django 3.2.4 on 2022-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0027_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('general_credit', 'semester_type', 'year'), name='semester already exists in plan.'),
        ),
    ]
