# Generated by Django 3.2.4 on 2022-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0028_auto_20220424_1411'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='semester already exists in plan.',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('plan', 'semester_type', 'year'), name='unique_semester_plan'),
        ),
    ]
