# Generated by Django 3.2.4 on 2022-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0030_alter_semester_semester_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_semester_plan',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('first', 'first'), ('second', 'second'), ('summer', 'summer'), ('winter', 'winter'), ('all', 'all')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('plan', 'semester_type', 'year')},
        ),
    ]
