# Generated by Django 3.2.4 on 2022-04-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0032_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
    ]
