# Generated by Django 3.2.4 on 2022-05-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0034_auto_20220501_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditchangehistory',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='creditchangehistory',
            name='major',
        ),
        migrations.RemoveField(
            model_name='lecturetypechangehistory',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecturetypechangehistory',
            name='major',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planmajor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='planmajor',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='plan',
        ),
    ]
