# Generated by Django 3.2.4 on 2022-05-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
        ('lecture', '0035_auto_20220502_0644'),
        ('requirement', '0011_auto_20220502_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterlecture',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='semester.semester'),
        ),
        migrations.DeleteModel(
            name='CreditChangeHistory',
        ),
        migrations.DeleteModel(
            name='LectureTypeChangeHistory',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanMajor',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
