# Generated by Django 3.2.4 on 2022-05-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0038_alter_semesterlecture_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterlecture',
            name='semester',
        ),
    ]
