# Generated by Django 3.2.4 on 2022-05-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
        ('lecture', '0039_remove_semesterlecture_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterlecture',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesterlecture', to='semester.semester'),
            preserve_default=False,
        ),
    ]
