# Generated by Django 3.2.7 on 2021-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
