# Generated by Django 3.2.7 on 2021-09-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
