# Generated by Django 3.2.4 on 2022-05-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
