# Generated by Django 3.2.4 on 2022-05-01 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0004_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='user.user'),
            preserve_default=False,
        ),
    ]
