# Generated by Django 3.2.4 on 2022-05-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_alter_faq_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
    ]
